export const SET_TRENDING = 'SET_TRENDING';
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';
export const SET_LOADING = 'SET_LOADING';
export const RESET_FETCHED_PAGES = 'RESET_FETCHED_PAGES';
export const REMOVE_FROM_FETCHED_PAGES = 'REMOVE_FROM_FETCHED_PAGES';
export const SET_MOVIE_TYPE = 'SET_MOVIE_TYPE';
export const FETCH_ERROR = 'FETCH_ERROR';
